# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1359, 767)
        Form.setMouseTracking(True)
        self.net_connect_btn2 = QtWidgets.QPushButton(Form)
        self.net_connect_btn2.setGeometry(QtCore.QRect(760, 912, 101, 20))
        self.net_connect_btn2.setObjectName("net_connect_btn2")
        self.net_connect_btn2_2 = QtWidgets.QPushButton(Form)
        self.net_connect_btn2_2.setGeometry(QtCore.QRect(860, 910, 81, 20))
        self.net_connect_btn2_2.setObjectName("net_connect_btn2_2")
        self.label_door_title = QtWidgets.QLabel(Form)
        self.label_door_title.setGeometry(QtCore.QRect(10, 20, 51, 441))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_door_title.setFont(font)
        self.label_door_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_title.setObjectName("label_door_title")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(80, 10, 1271, 451))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_door_28 = QtWidgets.QLabel(self.widget)
        self.label_door_28.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_28.setMouseTracking(True)
        self.label_door_28.setAutoFillBackground(False)
        self.label_door_28.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_28.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_28.setLineWidth(1)
        self.label_door_28.setMidLineWidth(0)
        self.label_door_28.setText("")
        self.label_door_28.setObjectName("label_door_28")
        self.gridLayout.addWidget(self.label_door_28, 5, 7, 1, 1)
        self.label_door_name_40 = QtWidgets.QLabel(self.widget)
        self.label_door_name_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_40.setObjectName("label_door_name_40")
        self.gridLayout.addWidget(self.label_door_name_40, 4, 9, 1, 1)
        self.label_door_name_5 = QtWidgets.QLabel(self.widget)
        self.label_door_name_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_5.setObjectName("label_door_name_5")
        self.gridLayout.addWidget(self.label_door_name_5, 0, 4, 1, 1)
        self.label_door_name_1 = QtWidgets.QLabel(self.widget)
        self.label_door_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_1.setObjectName("label_door_name_1")
        self.gridLayout.addWidget(self.label_door_name_1, 0, 0, 1, 1)
        self.label_door_name_6 = QtWidgets.QLabel(self.widget)
        self.label_door_name_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_6.setObjectName("label_door_name_6")
        self.gridLayout.addWidget(self.label_door_name_6, 0, 5, 1, 1)
        self.label_door_name_8 = QtWidgets.QLabel(self.widget)
        self.label_door_name_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_8.setObjectName("label_door_name_8")
        self.gridLayout.addWidget(self.label_door_name_8, 0, 7, 1, 1)
        self.label_door_name_7 = QtWidgets.QLabel(self.widget)
        self.label_door_name_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_7.setObjectName("label_door_name_7")
        self.gridLayout.addWidget(self.label_door_name_7, 0, 6, 1, 1)
        self.label_door_name_9 = QtWidgets.QLabel(self.widget)
        self.label_door_name_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_9.setObjectName("label_door_name_9")
        self.gridLayout.addWidget(self.label_door_name_9, 0, 8, 1, 1)
        self.label_door_name_2 = QtWidgets.QLabel(self.widget)
        self.label_door_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_2.setObjectName("label_door_name_2")
        self.gridLayout.addWidget(self.label_door_name_2, 0, 1, 1, 1)
        self.label_door_name_31 = QtWidgets.QLabel(self.widget)
        self.label_door_name_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_31.setObjectName("label_door_name_31")
        self.gridLayout.addWidget(self.label_door_name_31, 4, 0, 1, 1)
        self.label_door_21 = QtWidgets.QLabel(self.widget)
        self.label_door_21.setMinimumSize(QtCore.QSize(0, 110))
        self.label_door_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_21.setMouseTracking(True)
        self.label_door_21.setAutoFillBackground(False)
        self.label_door_21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_21.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_21.setLineWidth(1)
        self.label_door_21.setMidLineWidth(0)
        self.label_door_21.setText("")
        self.label_door_21.setObjectName("label_door_21")
        self.gridLayout.addWidget(self.label_door_21, 5, 0, 1, 1)
        self.label_door_13 = QtWidgets.QLabel(self.widget)
        self.label_door_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_13.setMouseTracking(True)
        self.label_door_13.setAutoFillBackground(False)
        self.label_door_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_13.setLineWidth(1)
        self.label_door_13.setMidLineWidth(0)
        self.label_door_13.setText("")
        self.label_door_13.setObjectName("label_door_13")
        self.gridLayout.addWidget(self.label_door_13, 3, 2, 1, 1)
        self.label_door_1 = QtWidgets.QLabel(self.widget)
        self.label_door_1.setMinimumSize(QtCore.QSize(0, 110))
        self.label_door_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_1.setMouseTracking(True)
        self.label_door_1.setAutoFillBackground(False)
        self.label_door_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_1.setLineWidth(1)
        self.label_door_1.setMidLineWidth(0)
        self.label_door_1.setText("")
        self.label_door_1.setObjectName("label_door_1")
        self.gridLayout.addWidget(self.label_door_1, 1, 0, 1, 1)
        self.label_door_17 = QtWidgets.QLabel(self.widget)
        self.label_door_17.setMinimumSize(QtCore.QSize(0, 120))
        self.label_door_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_17.setMouseTracking(True)
        self.label_door_17.setAutoFillBackground(False)
        self.label_door_17.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_17.setLineWidth(1)
        self.label_door_17.setMidLineWidth(0)
        self.label_door_17.setText("")
        self.label_door_17.setObjectName("label_door_17")
        self.gridLayout.addWidget(self.label_door_17, 3, 6, 1, 1)
        self.label_door_20 = QtWidgets.QLabel(self.widget)
        self.label_door_20.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_20.setMouseTracking(True)
        self.label_door_20.setAutoFillBackground(False)
        self.label_door_20.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_20.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_20.setLineWidth(1)
        self.label_door_20.setMidLineWidth(0)
        self.label_door_20.setText("")
        self.label_door_20.setObjectName("label_door_20")
        self.gridLayout.addWidget(self.label_door_20, 3, 9, 1, 1)
        self.label_door_name_33 = QtWidgets.QLabel(self.widget)
        self.label_door_name_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_33.setObjectName("label_door_name_33")
        self.gridLayout.addWidget(self.label_door_name_33, 4, 2, 1, 1)
        self.label_door_14 = QtWidgets.QLabel(self.widget)
        self.label_door_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_14.setMouseTracking(True)
        self.label_door_14.setAutoFillBackground(False)
        self.label_door_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_14.setLineWidth(1)
        self.label_door_14.setMidLineWidth(0)
        self.label_door_14.setText("")
        self.label_door_14.setObjectName("label_door_14")
        self.gridLayout.addWidget(self.label_door_14, 3, 3, 1, 1)
        self.label_door_11 = QtWidgets.QLabel(self.widget)
        self.label_door_11.setMinimumSize(QtCore.QSize(0, 110))
        self.label_door_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_11.setMouseTracking(True)
        self.label_door_11.setAutoFillBackground(False)
        self.label_door_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_11.setLineWidth(1)
        self.label_door_11.setMidLineWidth(0)
        self.label_door_11.setText("")
        self.label_door_11.setObjectName("label_door_11")
        self.gridLayout.addWidget(self.label_door_11, 3, 0, 1, 1)
        self.label_door_name_32 = QtWidgets.QLabel(self.widget)
        self.label_door_name_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_32.setObjectName("label_door_name_32")
        self.gridLayout.addWidget(self.label_door_name_32, 4, 1, 1, 1)
        self.label_door_19 = QtWidgets.QLabel(self.widget)
        self.label_door_19.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_19.setMouseTracking(True)
        self.label_door_19.setAutoFillBackground(False)
        self.label_door_19.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_19.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_19.setLineWidth(1)
        self.label_door_19.setMidLineWidth(0)
        self.label_door_19.setText("")
        self.label_door_19.setObjectName("label_door_19")
        self.gridLayout.addWidget(self.label_door_19, 3, 8, 1, 1)
        self.label_door_name_10 = QtWidgets.QLabel(self.widget)
        self.label_door_name_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_10.setObjectName("label_door_name_10")
        self.gridLayout.addWidget(self.label_door_name_10, 0, 9, 1, 1)
        self.label_door_12 = QtWidgets.QLabel(self.widget)
        self.label_door_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_12.setMouseTracking(True)
        self.label_door_12.setAutoFillBackground(False)
        self.label_door_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_12.setLineWidth(1)
        self.label_door_12.setMidLineWidth(0)
        self.label_door_12.setText("")
        self.label_door_12.setObjectName("label_door_12")
        self.gridLayout.addWidget(self.label_door_12, 3, 1, 1, 1)
        self.label_door_15 = QtWidgets.QLabel(self.widget)
        self.label_door_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_15.setMouseTracking(True)
        self.label_door_15.setAutoFillBackground(False)
        self.label_door_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_15.setLineWidth(1)
        self.label_door_15.setMidLineWidth(0)
        self.label_door_15.setText("")
        self.label_door_15.setObjectName("label_door_15")
        self.gridLayout.addWidget(self.label_door_15, 3, 4, 1, 1)
        self.label_door_name_15 = QtWidgets.QLabel(self.widget)
        self.label_door_name_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_15.setObjectName("label_door_name_15")
        self.gridLayout.addWidget(self.label_door_name_15, 2, 4, 1, 1)
        self.label_door_18 = QtWidgets.QLabel(self.widget)
        self.label_door_18.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_18.setMouseTracking(True)
        self.label_door_18.setAutoFillBackground(False)
        self.label_door_18.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_18.setLineWidth(1)
        self.label_door_18.setMidLineWidth(0)
        self.label_door_18.setText("")
        self.label_door_18.setObjectName("label_door_18")
        self.gridLayout.addWidget(self.label_door_18, 3, 7, 1, 1)
        self.label_door_name_17 = QtWidgets.QLabel(self.widget)
        self.label_door_name_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_17.setObjectName("label_door_name_17")
        self.gridLayout.addWidget(self.label_door_name_17, 2, 6, 1, 1)
        self.label_door_name_12 = QtWidgets.QLabel(self.widget)
        self.label_door_name_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_12.setObjectName("label_door_name_12")
        self.gridLayout.addWidget(self.label_door_name_12, 2, 1, 1, 1)
        self.label_door_name_14 = QtWidgets.QLabel(self.widget)
        self.label_door_name_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_14.setObjectName("label_door_name_14")
        self.gridLayout.addWidget(self.label_door_name_14, 2, 3, 1, 1)
        self.label_door_name_34 = QtWidgets.QLabel(self.widget)
        self.label_door_name_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_34.setObjectName("label_door_name_34")
        self.gridLayout.addWidget(self.label_door_name_34, 4, 3, 1, 1)
        self.label_door_name_11 = QtWidgets.QLabel(self.widget)
        self.label_door_name_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_11.setObjectName("label_door_name_11")
        self.gridLayout.addWidget(self.label_door_name_11, 2, 0, 1, 1)
        self.label_door_name_18 = QtWidgets.QLabel(self.widget)
        self.label_door_name_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_18.setObjectName("label_door_name_18")
        self.gridLayout.addWidget(self.label_door_name_18, 2, 7, 1, 1)
        self.label_door_name_16 = QtWidgets.QLabel(self.widget)
        self.label_door_name_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_16.setObjectName("label_door_name_16")
        self.gridLayout.addWidget(self.label_door_name_16, 2, 5, 1, 1)
        self.label_door_22 = QtWidgets.QLabel(self.widget)
        self.label_door_22.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_22.setMouseTracking(True)
        self.label_door_22.setAutoFillBackground(False)
        self.label_door_22.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_22.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_22.setLineWidth(1)
        self.label_door_22.setMidLineWidth(0)
        self.label_door_22.setText("")
        self.label_door_22.setObjectName("label_door_22")
        self.gridLayout.addWidget(self.label_door_22, 5, 1, 1, 1)
        self.label_door_24 = QtWidgets.QLabel(self.widget)
        self.label_door_24.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_24.setMouseTracking(True)
        self.label_door_24.setAutoFillBackground(False)
        self.label_door_24.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_24.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_24.setLineWidth(1)
        self.label_door_24.setMidLineWidth(0)
        self.label_door_24.setText("")
        self.label_door_24.setObjectName("label_door_24")
        self.gridLayout.addWidget(self.label_door_24, 5, 3, 1, 1)
        self.label_door_16 = QtWidgets.QLabel(self.widget)
        self.label_door_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_16.setMouseTracking(True)
        self.label_door_16.setAutoFillBackground(False)
        self.label_door_16.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_16.setLineWidth(1)
        self.label_door_16.setMidLineWidth(0)
        self.label_door_16.setText("")
        self.label_door_16.setObjectName("label_door_16")
        self.gridLayout.addWidget(self.label_door_16, 3, 5, 1, 1)
        self.label_door_name_38 = QtWidgets.QLabel(self.widget)
        self.label_door_name_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_38.setObjectName("label_door_name_38")
        self.gridLayout.addWidget(self.label_door_name_38, 4, 7, 1, 1)
        self.label_door_name_19 = QtWidgets.QLabel(self.widget)
        self.label_door_name_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_19.setObjectName("label_door_name_19")
        self.gridLayout.addWidget(self.label_door_name_19, 2, 8, 1, 1)
        self.label_door_name_37 = QtWidgets.QLabel(self.widget)
        self.label_door_name_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_37.setObjectName("label_door_name_37")
        self.gridLayout.addWidget(self.label_door_name_37, 4, 6, 1, 1)
        self.label_door_26 = QtWidgets.QLabel(self.widget)
        self.label_door_26.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_26.setMouseTracking(True)
        self.label_door_26.setAutoFillBackground(False)
        self.label_door_26.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_26.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_26.setLineWidth(1)
        self.label_door_26.setMidLineWidth(0)
        self.label_door_26.setText("")
        self.label_door_26.setObjectName("label_door_26")
        self.gridLayout.addWidget(self.label_door_26, 5, 5, 1, 1)
        self.label_door_name_35 = QtWidgets.QLabel(self.widget)
        self.label_door_name_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_35.setObjectName("label_door_name_35")
        self.gridLayout.addWidget(self.label_door_name_35, 4, 4, 1, 1)
        self.label_door_name_36 = QtWidgets.QLabel(self.widget)
        self.label_door_name_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_36.setObjectName("label_door_name_36")
        self.gridLayout.addWidget(self.label_door_name_36, 4, 5, 1, 1)
        self.label_door_27 = QtWidgets.QLabel(self.widget)
        self.label_door_27.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_27.setMouseTracking(True)
        self.label_door_27.setAutoFillBackground(False)
        self.label_door_27.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_27.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_27.setLineWidth(1)
        self.label_door_27.setMidLineWidth(0)
        self.label_door_27.setText("")
        self.label_door_27.setObjectName("label_door_27")
        self.gridLayout.addWidget(self.label_door_27, 5, 6, 1, 1)
        self.label_door_name_20 = QtWidgets.QLabel(self.widget)
        self.label_door_name_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_20.setObjectName("label_door_name_20")
        self.gridLayout.addWidget(self.label_door_name_20, 2, 9, 1, 1)
        self.label_door_23 = QtWidgets.QLabel(self.widget)
        self.label_door_23.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_23.setMouseTracking(True)
        self.label_door_23.setAutoFillBackground(False)
        self.label_door_23.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_23.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_23.setLineWidth(1)
        self.label_door_23.setMidLineWidth(0)
        self.label_door_23.setText("")
        self.label_door_23.setObjectName("label_door_23")
        self.gridLayout.addWidget(self.label_door_23, 5, 2, 1, 1)
        self.label_door_name_39 = QtWidgets.QLabel(self.widget)
        self.label_door_name_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_39.setObjectName("label_door_name_39")
        self.gridLayout.addWidget(self.label_door_name_39, 4, 8, 1, 1)
        self.label_door_25 = QtWidgets.QLabel(self.widget)
        self.label_door_25.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_25.setMouseTracking(True)
        self.label_door_25.setAutoFillBackground(False)
        self.label_door_25.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_25.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_25.setLineWidth(1)
        self.label_door_25.setMidLineWidth(0)
        self.label_door_25.setText("")
        self.label_door_25.setObjectName("label_door_25")
        self.gridLayout.addWidget(self.label_door_25, 5, 4, 1, 1)
        self.label_door_30 = QtWidgets.QLabel(self.widget)
        self.label_door_30.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_30.setMouseTracking(True)
        self.label_door_30.setAutoFillBackground(False)
        self.label_door_30.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_30.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_30.setLineWidth(1)
        self.label_door_30.setMidLineWidth(0)
        self.label_door_30.setText("")
        self.label_door_30.setObjectName("label_door_30")
        self.gridLayout.addWidget(self.label_door_30, 5, 9, 1, 1)
        self.label_door_29 = QtWidgets.QLabel(self.widget)
        self.label_door_29.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_29.setMouseTracking(True)
        self.label_door_29.setAutoFillBackground(False)
        self.label_door_29.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_29.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_29.setLineWidth(1)
        self.label_door_29.setMidLineWidth(0)
        self.label_door_29.setText("")
        self.label_door_29.setObjectName("label_door_29")
        self.gridLayout.addWidget(self.label_door_29, 5, 8, 1, 1)
        self.label_door_name_13 = QtWidgets.QLabel(self.widget)
        self.label_door_name_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_13.setObjectName("label_door_name_13")
        self.gridLayout.addWidget(self.label_door_name_13, 2, 2, 1, 1)
        self.label_door_8 = QtWidgets.QLabel(self.widget)
        self.label_door_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_8.setMouseTracking(True)
        self.label_door_8.setAutoFillBackground(False)
        self.label_door_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_8.setLineWidth(1)
        self.label_door_8.setMidLineWidth(0)
        self.label_door_8.setText("")
        self.label_door_8.setObjectName("label_door_8")
        self.gridLayout.addWidget(self.label_door_8, 1, 7, 1, 1)
        self.label_door_5 = QtWidgets.QLabel(self.widget)
        self.label_door_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_5.setMouseTracking(True)
        self.label_door_5.setAutoFillBackground(False)
        self.label_door_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_5.setLineWidth(1)
        self.label_door_5.setMidLineWidth(0)
        self.label_door_5.setText("")
        self.label_door_5.setObjectName("label_door_5")
        self.gridLayout.addWidget(self.label_door_5, 1, 4, 1, 1)
        self.label_door_name_3 = QtWidgets.QLabel(self.widget)
        self.label_door_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_3.setObjectName("label_door_name_3")
        self.gridLayout.addWidget(self.label_door_name_3, 0, 2, 1, 1)
        self.label_door_9 = QtWidgets.QLabel(self.widget)
        self.label_door_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_9.setMouseTracking(True)
        self.label_door_9.setAutoFillBackground(False)
        self.label_door_9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_9.setLineWidth(1)
        self.label_door_9.setMidLineWidth(0)
        self.label_door_9.setText("")
        self.label_door_9.setObjectName("label_door_9")
        self.gridLayout.addWidget(self.label_door_9, 1, 8, 1, 1)
        self.label_door_10 = QtWidgets.QLabel(self.widget)
        self.label_door_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_door_10.setBaseSize(QtCore.QSize(0, 0))
        self.label_door_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_10.setMouseTracking(True)
        self.label_door_10.setAutoFillBackground(False)
        self.label_door_10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_10.setLineWidth(1)
        self.label_door_10.setMidLineWidth(0)
        self.label_door_10.setText("")
        self.label_door_10.setObjectName("label_door_10")
        self.gridLayout.addWidget(self.label_door_10, 1, 9, 1, 1)
        self.label_door_2 = QtWidgets.QLabel(self.widget)
        self.label_door_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_2.setMouseTracking(True)
        self.label_door_2.setAutoFillBackground(False)
        self.label_door_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_2.setLineWidth(1)
        self.label_door_2.setMidLineWidth(0)
        self.label_door_2.setText("")
        self.label_door_2.setObjectName("label_door_2")
        self.gridLayout.addWidget(self.label_door_2, 1, 1, 1, 1)
        self.label_door_name_4 = QtWidgets.QLabel(self.widget)
        self.label_door_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_door_name_4.setObjectName("label_door_name_4")
        self.gridLayout.addWidget(self.label_door_name_4, 0, 3, 1, 1)
        self.label_door_3 = QtWidgets.QLabel(self.widget)
        self.label_door_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_3.setMouseTracking(True)
        self.label_door_3.setAutoFillBackground(False)
        self.label_door_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_3.setLineWidth(1)
        self.label_door_3.setMidLineWidth(0)
        self.label_door_3.setText("")
        self.label_door_3.setObjectName("label_door_3")
        self.gridLayout.addWidget(self.label_door_3, 1, 2, 1, 1)
        self.label_door_4 = QtWidgets.QLabel(self.widget)
        self.label_door_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_4.setMouseTracking(True)
        self.label_door_4.setAutoFillBackground(False)
        self.label_door_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_4.setLineWidth(1)
        self.label_door_4.setMidLineWidth(0)
        self.label_door_4.setText("")
        self.label_door_4.setObjectName("label_door_4")
        self.gridLayout.addWidget(self.label_door_4, 1, 3, 1, 1)
        self.label_door_7 = QtWidgets.QLabel(self.widget)
        self.label_door_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_7.setMouseTracking(True)
        self.label_door_7.setAutoFillBackground(False)
        self.label_door_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_7.setLineWidth(1)
        self.label_door_7.setMidLineWidth(0)
        self.label_door_7.setText("")
        self.label_door_7.setObjectName("label_door_7")
        self.gridLayout.addWidget(self.label_door_7, 1, 6, 1, 1)
        self.label_door_6 = QtWidgets.QLabel(self.widget)
        self.label_door_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_door_6.setMouseTracking(True)
        self.label_door_6.setAutoFillBackground(False)
        self.label_door_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_door_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_door_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_door_6.setLineWidth(1)
        self.label_door_6.setMidLineWidth(0)
        self.label_door_6.setText("")
        self.label_door_6.setObjectName("label_door_6")
        self.gridLayout.addWidget(self.label_door_6, 1, 5, 1, 1)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 470, 1346, 291))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.get0frame_btn = QtWidgets.QPushButton(self.widget1)
        self.get0frame_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.get0frame_btn.setObjectName("get0frame_btn")
        self.gridLayout_3.addWidget(self.get0frame_btn, 1, 0, 1, 1)
        self.getMframe_btn = QtWidgets.QPushButton(self.widget1)
        self.getMframe_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.getMframe_btn.setObjectName("getMframe_btn")
        self.gridLayout_3.addWidget(self.getMframe_btn, 2, 0, 1, 1)
        self.testbtn_2 = QtWidgets.QPushButton(self.widget1)
        self.testbtn_2.setMinimumSize(QtCore.QSize(0, 40))
        self.testbtn_2.setObjectName("testbtn_2")
        self.gridLayout_3.addWidget(self.testbtn_2, 5, 0, 1, 1)
        self.net_connect_btn = QtWidgets.QPushButton(self.widget1)
        self.net_connect_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.net_connect_btn.setObjectName("net_connect_btn")
        self.gridLayout_3.addWidget(self.net_connect_btn, 3, 0, 1, 1)
        self.open_cam_btn = QtWidgets.QPushButton(self.widget1)
        self.open_cam_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.open_cam_btn.setStyleSheet("")
        self.open_cam_btn.setObjectName("open_cam_btn")
        self.gridLayout_3.addWidget(self.open_cam_btn, 0, 0, 1, 1)
        self.testbtn = QtWidgets.QPushButton(self.widget1)
        self.testbtn.setMinimumSize(QtCore.QSize(0, 40))
        self.testbtn.setObjectName("testbtn")
        self.gridLayout_3.addWidget(self.testbtn, 4, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_index_sel = QtWidgets.QComboBox(self.widget1)
        self.comboBox_index_sel.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_index_sel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.comboBox_index_sel.setMaxCount(30)
        self.comboBox_index_sel.setObjectName("comboBox_index_sel")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.comboBox_index_sel.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_index_sel)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.set_detect_roi = QtWidgets.QPushButton(self.widget1)
        self.set_detect_roi.setMinimumSize(QtCore.QSize(100, 36))
        self.set_detect_roi.setMaximumSize(QtCore.QSize(100, 16777215))
        self.set_detect_roi.setObjectName("set_detect_roi")
        self.horizontalLayout.addWidget(self.set_detect_roi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit_information = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_information.setReadOnly(True)
        self.textEdit_information.setObjectName("textEdit_information")
        self.verticalLayout.addWidget(self.textEdit_information)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label_camera_title = QtWidgets.QLabel(self.widget1)
        self.label_camera_title.setMinimumSize(QtCore.QSize(54, 0))
        self.label_camera_title.setMaximumSize(QtCore.QSize(54, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_camera_title.setFont(font)
        self.label_camera_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_camera_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera_title.setObjectName("label_camera_title")
        self.horizontalLayout_2.addWidget(self.label_camera_title)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_imgsw_3 = QtWidgets.QLabel(self.widget1)
        self.label_imgsw_3.setMinimumSize(QtCore.QSize(320, 200))
        self.label_imgsw_3.setMaximumSize(QtCore.QSize(320, 16777215))
        self.label_imgsw_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_imgsw_3.setMouseTracking(True)
        self.label_imgsw_3.setAutoFillBackground(False)
        self.label_imgsw_3.setStyleSheet("")
        self.label_imgsw_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_imgsw_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_imgsw_3.setLineWidth(1)
        self.label_imgsw_3.setMidLineWidth(0)
        self.label_imgsw_3.setText("")
        self.label_imgsw_3.setObjectName("label_imgsw_3")
        self.gridLayout_2.addWidget(self.label_imgsw_3, 2, 2, 1, 1)
        self.textEdit_info = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_info.setMinimumSize(QtCore.QSize(320, 0))
        self.textEdit_info.setMaximumSize(QtCore.QSize(320, 35))
        self.textEdit_info.setReadOnly(True)
        self.textEdit_info.setObjectName("textEdit_info")
        self.gridLayout_2.addWidget(self.textEdit_info, 0, 0, 1, 1)
        self.label_imgsw = QtWidgets.QLabel(self.widget1)
        self.label_imgsw.setMinimumSize(QtCore.QSize(320, 235))
        self.label_imgsw.setMaximumSize(QtCore.QSize(320, 16777215))
        self.label_imgsw.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_imgsw.setMouseTracking(True)
        self.label_imgsw.setAutoFillBackground(False)
        self.label_imgsw.setStyleSheet("")
        self.label_imgsw.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_imgsw.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_imgsw.setLineWidth(1)
        self.label_imgsw.setMidLineWidth(0)
        self.label_imgsw.setText("")
        self.label_imgsw.setObjectName("label_imgsw")
        self.gridLayout_2.addWidget(self.label_imgsw, 2, 0, 1, 1)
        self.textEdit_info_2 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_info_2.setMinimumSize(QtCore.QSize(320, 0))
        self.textEdit_info_2.setMaximumSize(QtCore.QSize(320, 35))
        self.textEdit_info_2.setReadOnly(True)
        self.textEdit_info_2.setObjectName("textEdit_info_2")
        self.gridLayout_2.addWidget(self.textEdit_info_2, 0, 1, 1, 1)
        self.textEdit_info_3 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_info_3.setMinimumSize(QtCore.QSize(320, 0))
        self.textEdit_info_3.setMaximumSize(QtCore.QSize(320, 35))
        self.textEdit_info_3.setReadOnly(True)
        self.textEdit_info_3.setObjectName("textEdit_info_3")
        self.gridLayout_2.addWidget(self.textEdit_info_3, 0, 2, 1, 1)
        self.label_imgsw_2 = QtWidgets.QLabel(self.widget1)
        self.label_imgsw_2.setMinimumSize(QtCore.QSize(320, 0))
        self.label_imgsw_2.setMaximumSize(QtCore.QSize(320, 16777215))
        self.label_imgsw_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_imgsw_2.setMouseTracking(True)
        self.label_imgsw_2.setAutoFillBackground(False)
        self.label_imgsw_2.setStyleSheet("")
        self.label_imgsw_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_imgsw_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_imgsw_2.setLineWidth(1)
        self.label_imgsw_2.setMidLineWidth(0)
        self.label_imgsw_2.setText("")
        self.label_imgsw_2.setObjectName("label_imgsw_2")
        self.gridLayout_2.addWidget(self.label_imgsw_2, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)

        self.retranslateUi(Form)
        self.net_connect_btn.clicked.connect(Form.connectnet)
        self.net_connect_btn2.clicked.connect(Form.connectnet2)
        self.testbtn.clicked.connect(Form.testfunc)
        self.get0frame_btn.clicked.connect(Form.get0frame)
        self.getMframe_btn.clicked.connect(Form.getMframe)
        self.open_cam_btn.clicked.connect(Form.open_cam)
        self.set_detect_roi.clicked.connect(Form.slotcalldlg)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "异物检测系统"))
        self.net_connect_btn2.setText(_translate("Form", "net_connect2"))
        self.net_connect_btn2_2.setText(_translate("Form", "net_connect3"))
        self.label_door_title.setText(_translate("Form", "屏\n"
"蔽\n"
"门\n"
"状\n"
"态\n"
"显\n"
"示"))
        self.label_door_name_40.setText(_translate("Form", "30号门"))
        self.label_door_name_5.setText(_translate("Form", "5号门"))
        self.label_door_name_1.setText(_translate("Form", "1-号门"))
        self.label_door_name_6.setText(_translate("Form", "6号门"))
        self.label_door_name_8.setText(_translate("Form", "8号门"))
        self.label_door_name_7.setText(_translate("Form", "7号门"))
        self.label_door_name_9.setText(_translate("Form", "9号门"))
        self.label_door_name_2.setText(_translate("Form", "2号门"))
        self.label_door_name_31.setText(_translate("Form", "21号门"))
        self.label_door_name_33.setText(_translate("Form", "23号门"))
        self.label_door_name_32.setText(_translate("Form", "22号门"))
        self.label_door_name_10.setText(_translate("Form", "10号门"))
        self.label_door_name_15.setText(_translate("Form", "15号门"))
        self.label_door_name_17.setText(_translate("Form", "17号门"))
        self.label_door_name_12.setText(_translate("Form", "12号门"))
        self.label_door_name_14.setText(_translate("Form", "14号门"))
        self.label_door_name_34.setText(_translate("Form", "24号门"))
        self.label_door_name_11.setText(_translate("Form", "11号门"))
        self.label_door_name_18.setText(_translate("Form", "18号门"))
        self.label_door_name_16.setText(_translate("Form", "16号门"))
        self.label_door_name_38.setText(_translate("Form", "28号门"))
        self.label_door_name_19.setText(_translate("Form", "19号门"))
        self.label_door_name_37.setText(_translate("Form", "27号门"))
        self.label_door_name_35.setText(_translate("Form", "25号门"))
        self.label_door_name_36.setText(_translate("Form", "26号门"))
        self.label_door_name_20.setText(_translate("Form", "20号门"))
        self.label_door_name_39.setText(_translate("Form", "29号门"))
        self.label_door_name_13.setText(_translate("Form", "13号门"))
        self.label_door_name_3.setText(_translate("Form", "3号门"))
        self.label_door_name_4.setText(_translate("Form", "4号门"))
        self.get0frame_btn.setText(_translate("Form", "暂停"))
        self.getMframe_btn.setText(_translate("Form", "开始工作"))
        self.testbtn_2.setText(_translate("Form", "测试2"))
        self.net_connect_btn.setText(_translate("Form", "连接网络"))
        self.open_cam_btn.setText(_translate("Form", "连接前端"))
        self.testbtn.setText(_translate("Form", "测试1"))
        self.comboBox_index_sel.setCurrentText(_translate("Form", "1"))
        self.comboBox_index_sel.setItemText(0, _translate("Form", "1"))
        self.comboBox_index_sel.setItemText(1, _translate("Form", "2"))
        self.comboBox_index_sel.setItemText(2, _translate("Form", "3"))
        self.comboBox_index_sel.setItemText(3, _translate("Form", "4"))
        self.comboBox_index_sel.setItemText(4, _translate("Form", "5"))
        self.comboBox_index_sel.setItemText(5, _translate("Form", "6"))
        self.comboBox_index_sel.setItemText(6, _translate("Form", "7"))
        self.comboBox_index_sel.setItemText(7, _translate("Form", "8"))
        self.comboBox_index_sel.setItemText(8, _translate("Form", "9"))
        self.comboBox_index_sel.setItemText(9, _translate("Form", "10"))
        self.comboBox_index_sel.setItemText(10, _translate("Form", "11"))
        self.comboBox_index_sel.setItemText(11, _translate("Form", "12"))
        self.comboBox_index_sel.setItemText(12, _translate("Form", "13"))
        self.comboBox_index_sel.setItemText(13, _translate("Form", "14"))
        self.comboBox_index_sel.setItemText(14, _translate("Form", "15"))
        self.comboBox_index_sel.setItemText(15, _translate("Form", "16"))
        self.comboBox_index_sel.setItemText(16, _translate("Form", "17"))
        self.comboBox_index_sel.setItemText(17, _translate("Form", "18"))
        self.comboBox_index_sel.setItemText(18, _translate("Form", "19"))
        self.comboBox_index_sel.setItemText(19, _translate("Form", "20"))
        self.comboBox_index_sel.setItemText(20, _translate("Form", "21"))
        self.comboBox_index_sel.setItemText(21, _translate("Form", "22"))
        self.comboBox_index_sel.setItemText(22, _translate("Form", "23"))
        self.comboBox_index_sel.setItemText(23, _translate("Form", "24"))
        self.comboBox_index_sel.setItemText(24, _translate("Form", "25"))
        self.comboBox_index_sel.setItemText(25, _translate("Form", "26"))
        self.comboBox_index_sel.setItemText(26, _translate("Form", "27"))
        self.comboBox_index_sel.setItemText(27, _translate("Form", "28"))
        self.comboBox_index_sel.setItemText(28, _translate("Form", "29"))
        self.comboBox_index_sel.setItemText(29, _translate("Form", "30"))
        self.label.setText(_translate("Form", "号门"))
        self.set_detect_roi.setText(_translate("Form", "检测区设置"))
        self.label_camera_title.setText(_translate("Form", "告\n"
"警\n"
"设\n"
"像\n"
"头\n"
"显\n"
"示"))

