# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setroidlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dlg_setroi(object):
    def setupUi(self, Dlg_setroi):
        Dlg_setroi.setObjectName("Dlg_setroi")
        Dlg_setroi.resize(925, 678)
        Dlg_setroi.setMouseTracking(True)
        self.textEdit_information = QtWidgets.QTextEdit(Dlg_setroi)
        self.textEdit_information.setGeometry(QtCore.QRect(10, 495, 901, 176))
        self.textEdit_information.setReadOnly(True)
        self.textEdit_information.setObjectName("textEdit_information")
        self.label_imgsw = QtWidgets.QLabel(Dlg_setroi)
        self.label_imgsw.setGeometry(QtCore.QRect(10, 0, 640, 480))
        self.label_imgsw.setMinimumSize(QtCore.QSize(640, 480))
        self.label_imgsw.setMaximumSize(QtCore.QSize(640, 480))
        self.label_imgsw.setMouseTracking(True)
        self.label_imgsw.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_imgsw.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_imgsw.setText("")
        self.label_imgsw.setObjectName("label_imgsw")
        self.splitter_5 = QtWidgets.QSplitter(Dlg_setroi)
        self.splitter_5.setGeometry(QtCore.QRect(660, 0, 251, 481))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_index_sw = QtWidgets.QLabel(self.layoutWidget)
        self.label_index_sw.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_index_sw.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_index_sw.setText("")
        self.label_index_sw.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_index_sw.setObjectName("label_index_sw")
        self.horizontalLayout.addWidget(self.label_index_sw)
        self.label_index_sw_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_index_sw_2.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_2.setObjectName("label_index_sw_2")
        self.horizontalLayout.addWidget(self.label_index_sw_2)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_index_sw_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_index_sw_3.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_3.setObjectName("label_index_sw_3")
        self.verticalLayout_2.addWidget(self.label_index_sw_3)
        self.label_index_sw_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_index_sw_4.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_4.setObjectName("label_index_sw_4")
        self.verticalLayout_2.addWidget(self.label_index_sw_4)
        self.label_index_sw_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_index_sw_5.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_5.setObjectName("label_index_sw_5")
        self.verticalLayout_2.addWidget(self.label_index_sw_5)
        self.label_index_sw_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_index_sw_6.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_6.setObjectName("label_index_sw_6")
        self.verticalLayout_2.addWidget(self.label_index_sw_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_LT_x = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_LT_x.setMaxLength(4)
        self.lineEdit_LT_x.setObjectName("lineEdit_LT_x")
        self.verticalLayout.addWidget(self.lineEdit_LT_x)
        self.lineEdit_LT_y = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_LT_y.setMaxLength(4)
        self.lineEdit_LT_y.setObjectName("lineEdit_LT_y")
        self.verticalLayout.addWidget(self.lineEdit_LT_y)
        self.lineEdit_RB_x = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_RB_x.setMaxLength(4)
        self.lineEdit_RB_x.setObjectName("lineEdit_RB_x")
        self.verticalLayout.addWidget(self.lineEdit_RB_x)
        self.lineEdit_RB_y = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_RB_y.setMaxLength(4)
        self.lineEdit_RB_y.setObjectName("lineEdit_RB_y")
        self.verticalLayout.addWidget(self.lineEdit_RB_y)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.preview_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.preview_btn.setMinimumSize(QtCore.QSize(100, 36))
        self.preview_btn.setObjectName("preview_btn")
        self.horizontalLayout_7.addWidget(self.preview_btn)
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_index_sw_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_index_sw_9.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_9.setObjectName("label_index_sw_9")
        self.horizontalLayout_2.addWidget(self.label_index_sw_9)
        self.lineEdit_badWidth = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_badWidth.setMaxLength(4)
        self.lineEdit_badWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_badWidth.setObjectName("lineEdit_badWidth")
        self.horizontalLayout_2.addWidget(self.lineEdit_badWidth)
        self.label_index_sw_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_index_sw_10.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_10.setObjectName("label_index_sw_10")
        self.horizontalLayout_2.addWidget(self.label_index_sw_10)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_index_sw_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_index_sw_11.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_11.setObjectName("label_index_sw_11")
        self.horizontalLayout_4.addWidget(self.label_index_sw_11)
        self.lineEdit_badHeight = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_badHeight.setMaxLength(4)
        self.lineEdit_badHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_badHeight.setObjectName("lineEdit_badHeight")
        self.horizontalLayout_4.addWidget(self.lineEdit_badHeight)
        self.label_index_sw_14 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_index_sw_14.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_14.setObjectName("label_index_sw_14")
        self.horizontalLayout_4.addWidget(self.label_index_sw_14)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_index_sw_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_index_sw_13.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_13.setObjectName("label_index_sw_13")
        self.horizontalLayout_3.addWidget(self.label_index_sw_13)
        self.lineEdit_stdHeight = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_stdHeight.setMaxLength(4)
        self.lineEdit_stdHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_stdHeight.setObjectName("lineEdit_stdHeight")
        self.horizontalLayout_3.addWidget(self.lineEdit_stdHeight)
        self.label_index_sw_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_index_sw_12.setTextFormat(QtCore.Qt.RichText)
        self.label_index_sw_12.setObjectName("label_index_sw_12")
        self.horizontalLayout_3.addWidget(self.label_index_sw_12)
        self.layoutWidget4 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.set_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.set_btn.setMinimumSize(QtCore.QSize(100, 36))
        self.set_btn.setObjectName("set_btn")
        self.horizontalLayout_6.addWidget(self.set_btn)
        self.layoutWidget5 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.get1frame_btn = QtWidgets.QPushButton(self.layoutWidget5)
        self.get1frame_btn.setMinimumSize(QtCore.QSize(100, 36))
        self.get1frame_btn.setObjectName("get1frame_btn")
        self.horizontalLayout_8.addWidget(self.get1frame_btn)

        self.retranslateUi(Dlg_setroi)
        self.set_btn.clicked.connect(Dlg_setroi.set_detect_roi)
        self.lineEdit_LT_x.textChanged['QString'].connect(Dlg_setroi.check_input_LT_x)
        self.lineEdit_LT_y.textChanged['QString'].connect(Dlg_setroi.check_input_LT_y)
        self.lineEdit_RB_x.textChanged['QString'].connect(Dlg_setroi.check_input_RB_x)
        self.lineEdit_RB_y.textChanged['QString'].connect(Dlg_setroi.check_input_RB_y)
        self.preview_btn.clicked.connect(Dlg_setroi.pre_setting)
        self.get1frame_btn.clicked.connect(Dlg_setroi.get1frame)
        QtCore.QMetaObject.connectSlotsByName(Dlg_setroi)

    def retranslateUi(self, Dlg_setroi):
        _translate = QtCore.QCoreApplication.translate
        Dlg_setroi.setWindowTitle(_translate("Dlg_setroi", "设置检测区域"))
        self.label_index_sw_2.setText(_translate("Dlg_setroi", "号检测器设置"))
        self.label_index_sw_3.setText(_translate("Dlg_setroi", "X左上"))
        self.label_index_sw_4.setText(_translate("Dlg_setroi", "Y左上"))
        self.label_index_sw_5.setText(_translate("Dlg_setroi", "X右下"))
        self.label_index_sw_6.setText(_translate("Dlg_setroi", "Y右下"))
        self.lineEdit_LT_x.setText(_translate("Dlg_setroi", "1"))
        self.lineEdit_LT_y.setText(_translate("Dlg_setroi", "1"))
        self.lineEdit_RB_x.setText(_translate("Dlg_setroi", "200"))
        self.lineEdit_RB_y.setText(_translate("Dlg_setroi", "200"))
        self.preview_btn.setText(_translate("Dlg_setroi", "预览设置"))
        self.label_index_sw_9.setText(_translate("Dlg_setroi", "异物宽度"))
        self.lineEdit_badWidth.setText(_translate("Dlg_setroi", "150"))
        self.label_index_sw_10.setText(_translate("Dlg_setroi", "像素"))
        self.label_index_sw_11.setText(_translate("Dlg_setroi", "异物高度"))
        self.lineEdit_badHeight.setText(_translate("Dlg_setroi", "150"))
        self.label_index_sw_14.setText(_translate("Dlg_setroi", "毫米"))
        self.label_index_sw_13.setText(_translate("Dlg_setroi", "标准高度"))
        self.lineEdit_stdHeight.setText(_translate("Dlg_setroi", "2000"))
        self.label_index_sw_12.setText(_translate("Dlg_setroi", "毫米"))
        self.set_btn.setText(_translate("Dlg_setroi", "设置"))
        self.get1frame_btn.setText(_translate("Dlg_setroi", "采集图像"))

